apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger-system
spec:
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      version: 1.12.1
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  interval: 1m
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  values:
    meshProvider: kubernetes
    metricsServer: http://kube-prometheus-stack-prometheus.monitoring:9090
    loglevel: debug

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: flagger-system
spec:
  releaseName: flagger-loadtester
  chart:
    spec:
      chart: loadtester
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  interval: 1m
  dependsOn:
    - name: flagger